### ISSUE TITLE
Open or Pending Tickets

### ISSUE THREAD

**Issue by JujuBois** [RamgeSoft/Atera-Dashboard#1]
Hello,
Thank you for your work. However, I have the impression that the dashboard doesn't display pending tickets, but only open ones in my case.
I tried changing the URL to https://app.atera.com/api/v3/tickets?ticketStatus=Open&ticketStatus=Pending, but it doesn't work.

Thank you.

**Comment by Andy-dev-rs** [comment]
Hello,
thank you for your feedback!

I pushed an update, with this update you can easily add more ticketStatus via a new array:
`
$ticketStatuses = ['Open', 'Pending', 'Waiting for Technician', 'Waiting for Customer'];
`

**Comment by JujuBois** [comment]
Great, thanks, but I think there's still a problem with the overall picture ;)

![Image](https://github.com/user-attachments/assets/c58ed02d-47d0-40ee-8638-2eb5283dd437)

**Comment by Andy-dev-rs** [comment]
Hello, also fixed in the new push.
Added the count correctly and rendered it on clientside

**Comment by JujuBois** [comment]
Sorry, no work for me 

![Image](https://github.com/user-attachments/assets/62e748d6-7b63-4ffe-8d58-83f31b91a1a7)

**Comment by Andy-dev-rs** [comment]
Do you also used the new html file there?

**Comment by JujuBois** [comment]
I just redid the test, yes I have the latest version of the 2 files

**Comment by Andy-dev-rs** [comment]
Good Day, the last push should fix it

**Comment by JujuBois** [comment]
Great, it works
